name: 🛠️ Tauri Build & Release

on:
  push:
    branches: [ "main" ]  # or "release" if that's your default
  workflow_dispatch:      # lets you manually trigger from the GitHub UI

permissions:
  contents: write         # Needed to upload to GitHub Releases

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies (if Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            xdg-utils

      - name: Install frontend dependencies
        run: npm install

      - name: Build and release with Tauri
        uses: tauri-apps/tauri-action@v0
        with:
          args: --target ${{ matrix.platform == 'windows-latest' && 'x86_64-pc-windows-gnu' || '' }}

